version: '3'
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "4840:4840"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always
    depends_on:
      - redis
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data