name: Checks

on: [push]

jobs:

  publish-apiua:
    needs: test-docker-compose-with-build
    name: Publish APIUA to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image opcuaserver
        working-directory: ./api
        run: docker build . --file Dockerfile --tag api:latest
        
      - name: Build Latest opcuaserver Docker image
        working-directory: ./api
        run: docker tag opcuaserver:latest joaoribeiro5039/apiua:latest

      - name: Docker Push Latest opcuaserver
        run: docker push joaoribeiro5039/apiua:latest
  
              